### ISSUE TITLE
`init_device(fid)` not working with webcam on `/dev/video0`

### ISSUE THREAD

**Issue by dehann** [Affie/Video4Linux.jl#4]
Hi,

Just thought I'd list an issue that I am seeing, although I don't have an answer to help fix it just yet. From the README example, I'm trying to read an image from the laptop webcam. The webcam does exist at `/dev/video0` and can be read via VLC Capture Device mode just fine. It fails pretty hard though, dropped out of Julia. Using Ubuntu 16.04.

```julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.6.0 (2017-06-19 13:05 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-pc-linux-gnu

julia> using Video4Linux
depfile = joinpath(dirname(@__FILE__()), "../deps/loadpath.jl") = "/home/dehann/.julia/v0.6/Video4Linux/src/../deps/loadpath.jl"

julia> using ImageView

julia> using Colors, ColorTypes

julia> # Warning! no memory and device protection is implemented yet, therefore doing things out of order will cause julia to crash!
       ## set io method to read()
       set_io_method(Int64(0))

julia> ## open device
       fid = open_device("/dev/video0")
17

julia> ## init_device(fd, force_format);

julia> init_device(fid)
Device does not support read i/o
dehann@mrg-galago-01:~$ 
```

**Comment by Affie** [comment]
Hello Dehann,
It looks like the device does not support read io and probably only mmap. The io method can be set using the defined enumerated type `set_io_method(Video4Linux.IO_METHOD_MMAP)`.

I removed the exit (https://github.com/Affie/Video4Linux.jl/pull/6),  but it needs to be replaced by some other means of error checking. I don't know what the best method of protecting julia is yet. 
I'm going to close this issue and open a new one to address this

**Comment by dehann** [comment]
Unfortunately not, I will have to dig a bit deeper on this computer to see what is happening.

**Comment by dehann** [comment]
Hi, I misread sorry, the `set_io_method(Video4Linux.IO_METHOD_MMAP)` approach does clear this error.
