### ISSUE TITLE
Object files should be compiled localy not kept in repo

### ISSUE THREAD

**Issue by dehann** [Affie/Video4Linux.jl#9]
Not sure if this was intentional, but compiled object files should probably not be in the repo. The C we can look at compiling the C file with `Pkg.build()` during the package installation process:
```julia
From https://github.com/Affie/Video4Linux.jl
   5273095..e5ee4d7  master     -> origin/master
 * [new branch]      test/expand -> origin/test/expand
Updating 5273095..e5ee4d7
Fast-forward
...
 deps/v4lcapture/src/v4lcapture.o | Bin 15632 -> 0 bytes
...
```
That said, I'm not seeing that file on my local repo on master (so likely in the git history somewhere). Doesn't really matter if the object file has already been removed.

**Comment by Affie** [comment]
I agree, that one snuck in there and was never referenced by build. 
Was removed in https://github.com/Affie/Video4Linux.jl/pull/5
